version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 90
    labels:
      - "dependencies"
      - "no-changelog"
    milestone: 7
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/webapp"
    cooldown:
      semver-major-days: 90
      semver-minor-days: 21
      semver-patch-days: 3
    labels:
      - "dependencies"
      - "webapp"
    milestone: 7
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"

  - package-ecosystem: "pip"
    directories: [
      "/scripts",
      "/tools",
    ]
    cooldown:
      semver-major-days: 90
      semver-minor-days: 21
      semver-patch-days: 3
      exclude:
        - "tzdata"
    labels:
      - "dependencies"
      - "tools"
    milestone: 7
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
