repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: esphome\.yaml$
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: local
  #   hooks:
  #     - id: local-biome-lint
  #       name: biome lint
  #       language: system
  #       entry: bash -c 'cd webapp && exec npx biome lint --staged --write --files-ignore-unknown=true --no-errors-on-unmatched'
  #       types: [text]
  #       files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
