name: Tests

on:
  merge_group:
    types:
      - checks_requested

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  animation-splitter:
    name: Animation splitter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tools/

      - run: |
          cat <<EOL > Animation.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: python -m frekvens.AnimationSplitter --input Animation.csv

      - uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: "Animation-1.csv, Animation-2.csv"

  art-net-streamer:
    name: Art-Net streamer
    needs: distributed-display-protocol-streamer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tools/

      - run: |
          cat <<EOL > Drawing.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: |
          set +e
          OUTPUT=$(python -m frekvens.ArtNetStreamer --host localhost --input Drawing.csv 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "httpx.ConnectError"; then
            echo "Expected ConnectError occurred."
            exit 0
          fi
          echo "Unexpected error or no error."
          exit $STATUS

  distributed-display-protocol-streamer:
    name: Distributed Display Protocol streamer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tools/

      - run: |
          cat <<EOL > Drawing.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: |
          set +e
          OUTPUT=$(python -m frekvens.DistributedDisplayProtocolStreamer --host localhost --input Drawing.csv 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "httpx.ConnectError"; then
            echo "Expected ConnectError occurred."
            exit 0
          fi
          echo "Unexpected error or no error."
          exit $STATUS

  e131-streamer:
    name: E1.31 streamer
    needs: art-net-streamer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tools/

      - run: |
          cat <<EOL > Drawing.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: |
          set +e
          OUTPUT=$(python -m frekvens.E131Streamer --host localhost --input Drawing.csv 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "httpx.ConnectError"; then
            echo "Expected ConnectError occurred."
            exit 0
          fi
          echo "Unexpected error or no error."
          exit $STATUS

  font-generator:
    name: Font generator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install -r extra/Python/requirements.txt

      - run: python extra/Python/FontGenerator.py --input DejaVuSans --size 8

      - uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: "DejaVuSansFont.cpp, DejaVuSansFont.h"

  home-thermometer-demo:
    name: Home thermometer demo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tools/

      - run: |
          set +e
          OUTPUT=$(python -m frekvens.HomeThermometerDemo --host localhost --indoor=22 --outdoor=8 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "httpx.ConnectError"; then
            echo "Expected ConnectError occurred."
            exit 0
          fi
          echo "Unexpected error or no error."
          exit $STATUS

  mode-generator-animation:
    name: Mode generator - animation
    needs: mode-generator-drawing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: |
          cat <<EOL > Animation.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: python extra/Python/ModeGenerator.py --input Animation.csv

      - uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: "AnimationMode.cpp, AnimationMode.h"

  mode-generator-drawing:
    name: Mode generator - drawing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: |
          cat <<EOL > Drawing.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

      - run: python extra/Python/ModeGenerator.py --input Drawing.csv

      - uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: "DrawingMode.cpp, DrawingMode.h"
